package com.everis.stepsdef;

import cucumber.api.java.en.When;
import cucumber.api.java.en.And;
import org.openqa.selenium.WebElement;


public class stepDefsWhen{ 
	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write \"([^\"]*)\" in Your message field$")
	public void iWriteHelloWorldInYourMessageField(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^write the Job title with \"([^\"]*)\"$")
	public void writeJobTitleWith(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I complete the Company with \"([^\"]*)\"$")
	public void iCompleteCompanyWith(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write \"([^\"]*)\" in the Email address$")
	public void iWriteInEmailAddress(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.8474126984126984
	 */
	@And("^I click the Search button$")
	public void iClickSearchButton() {
		WebElement obj = SearchInGooglePage.driver.findElement(SearchInGooglePage.Search);
		obj.click();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I choose \"([^\"]*)\" option in the Select field Label combo$")
	public void iChooseOptionInSelectFieldLabelCombo(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the field First Name with the value \"([^\"]*)\"$")
	public void iWriteFieldFirstNameWithValue(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I navigate to \"([^\"]*)\"$")
	public void iNavigateTo(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I complete the Search field with \"([^\"]*)\"$")
	public void iCompleteSearchFieldWith(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^the following text is parsed:$")
	public void followingTextIsParsed() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.7845602918586789
	 */
	@And("^I click the Send Message button$")
	public void iClickSendMessageButton() {
		WebElement obj = SendContactMessagePage.driver.findElement(SendContactMessagePage.SendMessage);
		obj.click();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the value \"([^\"]*)\" in Last Name$")
	public void iWriteValueInLastName(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.7902136723716537
	 */
	@And("^I write the value \"([^\"]*)\" on the Phone field$")
	public void iWriteValuePhoneField(String Phone) {
		WebElement obj = SendContactMessagePage.driver.findElement(SendContactMessagePage.Phone);
		if (!Phone.equals("")){
			obj.sendKeys(Phone);
		}else{
			obj.sendKeys("123456789 on");
		}
	}

}