package cinnamontest.stepdefs;

import com.google.inject.Inject;
import com.nttdata.cinnamon.driver.Driver;
import cinnamontest.pages.ClientDetailPage;
import cinnamontest.pages.SendContactMessagePage;
import io.cucumber.java.es.Cuando;
import io.cucumber.java.es.Y;
import org.openqa.selenium.interactions.Actions;
import cinnamontest.pages.SearchInGooglePage;
import cinnamontest.pages.LookMyOrdersPage;
import cinnamontest.pages.MakeOrderPage;


public class stepDefsCuando extends BaseStep{ 
	private final MakeOrderPage makeorderpage;

	private final SearchInGooglePage searchingooglepage;

	private final Driver driver;

	private final ClientDetailPage clientdetailpage;

	private final SendContactMessagePage sendcontactmessagepage;

	private final LookMyOrdersPage lookmyorderspage;


	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write \"([^\"]*)\" in Your message field$")
	public void iWriteHelloWorldInYourMessageField(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I find all of the .feature files$")
	public void iFindAllfeatureFiles() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^write the Job title with \"([^\"]*)\"$")
	public void writeJobTitleWith(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I complete the Company with \"([^\"]*)\"$")
	public void iCompleteCompanyWith(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I parse the prettified representation of each of them$")
	public void iParsePrettifiedRepresentationEachThem() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write \"([^\"]*)\" in the Email address$")
	public void iWriteInEmailAddress(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I click the Search button$")
	public void iClickSearchButton() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I choose \"([^\"]*)\" option in the Select field Label combo$")
	public void iChooseOptionInSelectFieldLabelCombo(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the field First Name with the value \"([^\"]*)\"$")
	public void iWriteFieldFirstNameWithValue(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I navigate to \"([^\"]*)\"$")
	public void iNavigateTo(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I complete the Search field with \"([^\"]*)\"$")
	public void iCompleteSearchFieldWith(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^the following text is parsed:$")
	public void followingTextIsParsed() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6567975252945697
	 */
	@And("^I click the Send Message button$")
	public void iClickSendMessageButton() {
		WebElement obj = this.sendcontactmessagepage.IclicktheSendMessagebutton;
		Actions actions = new Actions(driver);
		actions.doubleClick(obj).perform();
	}

	/** null
	 */
	@Inject
	public stepDefsCuando(final Driver driver, final ClientDetailPage clientdetailpage) {
		this.driver = driver;
		this.driver.init();
		this.clientdetailpage = clientdetailpage;
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the value \"([^\"]*)\" in Last Name$")
	public void iWriteValueInLastName(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the value \"([^\"]*)\" on the Phone field$")
	public void iWriteValuePhoneField(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

}