package cinnamontest.stepdefs;

import com.google.inject.Inject;
import com.nttdata.cinnamon.driver.Driver;
import cinnamontest.pages.LoggingInPage;
import cinnamontest.pages.GherkinFeatureLexerPage;
import cinnamontest.pages.NativeCJavaLexerPage;
import cinnamontest.pages.GherkinFeatureLexerparserPage;
import io.cucumber.java.en.When;
import io.cucumber.java.en.And;
import cinnamontest.pages.PrettyPrinterPage;
import org.openqa.selenium.interactions.Actions;
import cinnamontest.pages.FeatureTextPage;
import cinnamontest.pages.GherkinStepsParserPage;


public class stepDefsWhen extends BaseStep{ 
	private final LoggingInPage logginginpage;

	private final Driver driver;

	private final FeatureTextPage featuretextpage;

	private final GherkinStepsParserPage gherkinstepsparserpage;

	private final GherkinFeatureLexerparserPage gherkinfeaturelexerparserpage;

	private final NativeCJavaLexerPage nativecjavalexerpage;

	private final PrettyPrinterPage prettyprinterpage;

	private final GherkinFeatureLexerPage gherkinfeaturelexerpage;


	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6560100196199231
	 */
	@When("^the following text is parsed:$")
	public void followingTextIsParsed(String following) {
		this.gherkinfeaturelexerparserpage.following.setValue(following);
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6923950858599055
	 */
	@When("^I find all of the .feature files$")
	public void iFindAllfeatureFiles() {
		this.prettyprinterpage.%LOCATOR%.setValue(%LOCATOR%);
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6563569575782532
	 */
	@And("^I parse the prettified representation of each of them$")
	public void iParsePrettifiedRepresentationEachThem() {
		WebElement obj = this.prettyprinterpage.representation;
		Actions actions = new Actions(driver);
		actions.doubleClick(obj).perform();
	}

	/** null
	 */
	@Inject
	public stepDefsWhen(final Driver driver, final LoggingInPage logginginpage) {
		this.driver = driver;
		this.driver.init();
		this.logginginpage = logginginpage;
	}

}