package com.everis.stepsdef;

import cucumber.api.java.es.Entonces;
import cucumber.api.java.es.Y;


public class stepDefsEntonces{ 
	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^there should be no parse errors$")
	public void thereShouldBeNoParseErrors() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

}