package com.everis.stepsdef;

import cucumber.api.java.en.Given;
import cucumber.api.java.en.And;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import java.io.File;
import java.util.concurrent.TimeUnit;


public class stepDefsGiven{ 
	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.9212415483434754
	 */
	@And("^go to the \"([^\"]*)\"$")
	public void goTo(String url) {
		SearchInGooglePage.driver.get(url);
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^I have Cucumber's home dir defined in CUCUMBER_HOME$")
	public void iHaveCucumbersHomeDirDefinedInCUCUMBERHOME() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 1.0
	 */
	@Given("^Open firefox browser$")
	public void openFirefoxBrowser(String browser) {
		String myBrowser = browser.toUpperCase().trim();
		String pathToDriverServerDir = ""; //TODO
		
		if (myBrowser.contains("FIREFOX")){
			System.setProperty("webdriver.gecko.driver", pathToDriverServerDir+File.separator+"geckodriver.exe");
			SearchInGooglePage.driver = new FirefoxDriver();
		}else if (myBrowser.contains("CHROME")){
			System.setProperty("webdriver.chrome.driver", pathToDriverServerDir+File.separator+"chromedriver.exe");
			SearchInGooglePage.driver = new ChromeDriver();
		}else if (myBrowser.contains("IE") || myBrowser.contains("EXPLORER")){
			System.setProperty("webdriver.ie.driver", pathToDriverServerDir+File.separator+"IEDriverServer.exe");
			SearchInGooglePage.driver = new InternetExplorerDriver();
		}else if (myBrowser.contains("EDGE")){
			System.setProperty("webdriver.edge.driver", pathToDriverServerDir+File.separator+"msedgedriver.exe");
			SearchInGooglePage.driver = new EdgeDriver();
		}else{
			System.setProperty("webdriver.chrome.driver", pathToDriverServerDir+File.separator+"chromedriver.exe");
			SearchInGooglePage.driver = new ChromeDriver();
		}
		
		SearchInGooglePage.driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^a \"([^\"]*)\", "native" "root" parser$")
	public void enParser(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

}