package cinnamontest.stepdefs;

import com.google.inject.Inject;
import com.nttdata.cinnamon.driver.Driver;
import cinnamontest.pages.ClientDetailPage;
import io.cucumber.java.es.Cuando;
import io.cucumber.java.es.Y;
import cinnamontest.pages.SendContactMessagePage;
import cinnamontest.pages.SearchInGooglePage;
import cinnamontest.pages.LookMyOrdersPage;
import cinnamontest.pages.MakeOrderPage;


public class stepDefsEntonces extends BaseStep{ 
	private final MakeOrderPage makeorderpage;

	private final SearchInGooglePage searchingooglepage;

	private final Driver driver;

	private final ClientDetailPage clientdetailpage;

	private final SendContactMessagePage sendcontactmessagepage;

	private final LookMyOrdersPage lookmyorderspage;


	/** null
	 */
	@Inject
	public stepDefsEntonces(final Driver driver, final ClientDetailPage clientdetailpage) {
		this.driver = driver;
		this.driver.init();
		this.clientdetailpage = clientdetailpage;
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^there should be no parse errors$")
	public void thereShouldBeNoParseErrors() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^the following files should have errors:$")
	public void followingFilesShouldHaveErrors() {
		//TODO It was not possible to generate code for this operation
	}

}