package com.everis.stepsdef;

import cucumber.api.java.es.Dado;
import cucumber.api.java.es.Y;


public class stepDefsDado{ 
	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^the following text is parsed:$")
	public void followingTextIsParsed() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^there is a step$")
	public void thereIsStep() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^I have Cucumber's home dir defined in CUCUMBER_HOME$")
	public void iHaveCucumbersHomeDirDefinedInCUCUMBERHOME() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^a \"([^\"]*)\", "ruby" "root" parser$")
	public void enParser(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

}