package com.everis.stepsdef;

import cucumber.api.java.es.Cuando;
import cucumber.api.java.es.Y;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;


public class stepDefsCuando{ 
	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write \"([^\"]*)\" in Your message field$")
	public void iWriteHelloWorldInYourMessageField(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^write the Job title with \"([^\"]*)\"$")
	public void writeJobTitleWith(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I complete the Company with \"([^\"]*)\"$")
	public void iCompleteCompanyWith(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write \"([^\"]*)\" in the Email address$")
	public void iWriteInEmailAddress(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I click the Search button$")
	public void iClickSearchButton() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I choose \"([^\"]*)\" option in the Select field Label combo$")
	public void iChooseOptionInSelectFieldLabelCombo(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the field First Name with the value \"([^\"]*)\"$")
	public void iWriteFieldFirstNameWithValue(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I navigate to \"([^\"]*)\"$")
	public void iNavigateTo(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I complete the Search field with \"([^\"]*)\"$")
	public void iCompleteSearchFieldWith(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^the following text is parsed:$")
	public void followingTextIsParsed() {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6567975252945697
	 */
	@And("^I click the Send Message button$")
	public void iClickSendMessageButton() {
		WebElement obj = SendContactMessagePage.driver.findElement(SendContactMessagePage.IclicktheSendMessagebutton);
		Actions actions = new Actions(SendContactMessagePage.driver);
		actions.doubleClick(obj).perform();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the value \"([^\"]*)\" in Last Name$")
	public void iWriteValueInLastName(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I write the value \"([^\"]*)\" on the Phone field$")
	public void iWriteValuePhoneField(String aValue) {
		//TODO It was not possible to generate code for this operation
		throw new cucumber.api.PendingException();
	}

}