package cinnamontest.stepdefs;

import com.google.inject.Inject;
import com.nttdata.cinnamon.driver.Driver;
import cinnamontest.pages.LoggingInPage;
import cinnamontest.pages.GherkinFeatureLexerPage;
import io.cucumber.java.es.Dado;
import io.cucumber.java.es.Y;
import cinnamontest.pages.NativeCJavaLexerPage;
import cinnamontest.pages.GherkinFeatureLexerparserPage;
import cinnamontest.pages.PrettyPrinterPage;
import cinnamontest.pages.FeatureTextPage;
import cinnamontest.pages.GherkinStepsParserPage;


public class stepDefsDado extends BaseStep{ 
	private final LoggingInPage logginginpage;

	private final Driver driver;

	private final FeatureTextPage featuretextpage;

	private final GherkinStepsParserPage gherkinstepsparserpage;

	private final GherkinFeatureLexerparserPage gherkinfeaturelexerparserpage;

	private final NativeCJavaLexerPage nativecjavalexerpage;

	private final PrettyPrinterPage prettyprinterpage;

	private final GherkinFeatureLexerPage gherkinfeaturelexerpage;


	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^the following text is parsed:$")
	public void followingTextIsParsed() {
		//TODO It was not possible to generate code for this operation
	}

	/** null
	 */
	@Inject
	public stepDefsDado(final Driver driver, final LoggingInPage logginginpage) {
		this.driver = driver;
		this.driver.init();
		this.logginginpage = logginginpage;
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^there is a step$")
	public void thereIsStep() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^I have Cucumber's home dir defined in CUCUMBER_HOME$")
	public void iHaveCucumbersHomeDirDefinedInCUCUMBERHOME() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Given("^a \"([^\"]*)\", "ruby" "root" parser$")
	public void enParser(String aValue) {
		//TODO It was not possible to generate code for this operation
	}

}