package cinnamontest.stepdefs;

import com.google.inject.Inject;
import com.nttdata.cinnamon.driver.Driver;
import cinnamontest.pages.ClientDetailPage;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.And;
import cinnamontest.pages.SendContactMessagePage;


public class stepDefsThen extends BaseStep{ 
	private final Driver driver;

	private final ClientDetailPage clientdetailpage;

	private final SendContactMessagePage sendcontactmessagepage;


	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6561389182242913
	 */
	@Then("^there should be no parse errors$")
	public void thereShouldBeNoParseErrors(String time) {
		try {
			long timeAux = Long.parseLong(time);
			Thread.sleep(timeAux);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/** null
	 */
	@Inject
	public stepDefsThen(final Driver driver, final ClientDetailPage clientdetailpage) {
		this.driver = driver;
		this.driver.init();
		this.clientdetailpage = clientdetailpage;
	}

}