package cinnamontest.stepdefs;

import com.google.inject.Inject;
import com.nttdata.cinnamon.driver.Driver;
import cinnamontest.pages.LoggingInPage;
import cinnamontest.pages.GherkinFeatureLexerPage;
import cinnamontest.pages.NativeCJavaLexerPage;
import cinnamontest.pages.GherkinFeatureLexerparserPage;
import io.cucumber.java.es.Cuando;
import io.cucumber.java.es.Y;
import cinnamontest.pages.PrettyPrinterPage;
import cinnamontest.pages.FeatureTextPage;
import cinnamontest.pages.GherkinStepsParserPage;


public class stepDefsCuando extends BaseStep{ 
	private final LoggingInPage logginginpage;

	private final Driver driver;

	private final FeatureTextPage featuretextpage;

	private final GherkinStepsParserPage gherkinstepsparserpage;

	private final GherkinFeatureLexerparserPage gherkinfeaturelexerparserpage;

	private final NativeCJavaLexerPage nativecjavalexerpage;

	private final PrettyPrinterPage prettyprinterpage;

	private final GherkinFeatureLexerPage gherkinfeaturelexerpage;


	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^the following text is parsed:$")
	public void followingTextIsParsed() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@When("^I find all of the .feature files$")
	public void iFindAllfeatureFiles() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@And("^I parse the prettified representation of each of them$")
	public void iParsePrettifiedRepresentationEachThem() {
		//TODO It was not possible to generate code for this operation
	}

	/** null
	 */
	@Inject
	public stepDefsCuando(final Driver driver, final LoggingInPage logginginpage) {
		this.driver = driver;
		this.driver.init();
		this.logginginpage = logginginpage;
	}

}