package com.everis.stepsdef;

import cucumber.api.java.en.Then;
import cucumber.api.java.en.And;


public class stepDefsThen{ 
	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6561389182242913
	 */
	@Then("there should be no parse errors")
	public void thereShouldBeNoParseErrors(String time) {
		try {
			long timeAux = Long.parseLong(time);
			Thread.sleep(timeAux);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/** Method autogenerated by iBDD tool
	 *	 Code implemented with a probability of: 0.6671632260197362
	 */
	@Then("the following files should have errors:")
	public void followingFilesShouldHaveErrors(String time) {
		try {
			long timeAux = Long.parseLong(time);
			Thread.sleep(timeAux);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}