package cinnamontest.stepdefs;

import com.google.inject.Inject;
import com.nttdata.cinnamon.driver.Driver;
import cinnamontest.pages.LoggingInPage;
import cinnamontest.pages.GherkinFeatureLexerPage;
import io.cucumber.java.es.Cuando;
import io.cucumber.java.es.Y;
import cinnamontest.pages.NativeCJavaLexerPage;
import cinnamontest.pages.GherkinFeatureLexerparserPage;
import cinnamontest.pages.PrettyPrinterPage;
import cinnamontest.pages.FeatureTextPage;
import cinnamontest.pages.GherkinStepsParserPage;


public class stepDefsEntonces extends BaseStep{ 
	private final LoggingInPage logginginpage;

	private final Driver driver;

	private final FeatureTextPage featuretextpage;

	private final GherkinStepsParserPage gherkinstepsparserpage;

	private final GherkinFeatureLexerparserPage gherkinfeaturelexerparserpage;

	private final NativeCJavaLexerPage nativecjavalexerpage;

	private final PrettyPrinterPage prettyprinterpage;

	private final GherkinFeatureLexerPage gherkinfeaturelexerpage;


	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^there should be parse errors on lines 1 through 3$")
	public void thereShouldBeParseErrorsLinesThrough() {
		//TODO It was not possible to generate code for this operation
	}

	/** null
	 */
	@Inject
	public stepDefsEntonces(final Driver driver, final LoggingInPage logginginpage) {
		this.driver = driver;
		this.driver.init();
		this.logginginpage = logginginpage;
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^there should be no parse errors$")
	public void thereShouldBeNoParseErrors() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^there should be a parse error on line 1$")
	public void thereShouldBeParseErrorLine() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^the following files should have errors:$")
	public void followingFilesShouldHaveErrors() {
		//TODO It was not possible to generate code for this operation
	}

	/** Method autogenerated by iBDD tool
	 *	 No code could be implemented for this operation.
	 *	 Please retrain the AI model to support it or add code manually.
	 */
	@Then("^there should be parse errors on lines 1 and 2$")
	public void thereShouldBeParseErrorsLinesAnd() {
		//TODO It was not possible to generate code for this operation
	}

}